---
# Run this commands to get make a diff of settings
#   gsettings list-recursively > original.txt
#   diff <(cat original.txt) <(gsettings list-recursively)

- name: Set global keybindings
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.desktop.wm.keybindings switch-input-source "[]"
    - gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"


# - name: Set Nautilus preferences
#   command: "{{ item }}"
#   with_items:
#     - gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
#     - gsettings set org.gnome.nautilus.icon-view default-zoom-level 'smaller'
#     - gsettings set org.gnome.nautilus.list-view default-zoom-level 'smaller'
#     - gsettings set org.gnome.nautilus.list-view use-tree-view true
#     - gsettings set org.gnome.nautilus.preferences thumbnail-limit "uint64 5242880"
#     - gsettings set org.gnome.nautilus.icon-view thumbnail-size 64
