
- name: Enable Universe repository
  raw: apt-add-repository universe
  register: add_repo_result
  changed_when: "'distribution component enabled for all sources' in add_repo_result.stdout"
  until: add_repo_result.rc == 0
  retries: 3
  delay: 1
  when: ansible_distribution == 'Ubuntu'

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded
  when: ansible_distribution == 'Ubuntu'
