- name: Install Fedora specific packages
  when: ansible_distribution == 'Fedora'
  ansible.builtin.package:
    name:
      - yum-plugin-priorities
      - epel-release

- name: Install Ubuntu specific packages
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.package:
    name:
      - bambam # baby keyboard mashing software

- name: Install Jujhar's Software
  ansible.builtin.package:
    name:
      - audacity
      - bmon
      - build-essential
      - chrome-gnome-shell
      - chromium-browser
      - clamav
      - clamav-daemon
      - clamtk
      - conky
      - curl
      - filezilla
      - firefox
      - forensics-all
      - gcc
      - git
      - gimp
      - gnome
      - gnome-tweaks
      - golang-go
      - golint
      - grep
      - htop
      - inotify-tools
      - iotop
      - jq
      - lastpass-cli
      - libcanberra-gtk-module
      - liferea
      - make
      - mycli
      - nemo # nice file manager
      - nemo-fileroller
      - nemo-font-manager
      - nautilus-admin
      - nautilus-extension-gnome-terminal
      - nautilus-font-manager
      - nautilus-image-converter
      - nautilus-wipe
      - ncdu
      - neofetch # get system deets to flex on others
      - nethogs
      - net-tools
      - nmap
      - obs-studio # live stream tool
      - openvpn
      - pandoc
      - pass
      - picard # MusicBrainz audio files tagger
      - powertop
      - pwgen
      - python3-pip
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-vnc
      - restic # badass backup
      - rsync
      - shellcheck
      - socat
      - sox # Swiss army knife of sound processing
      - tar
      - terminator
      - tig
      - timewarrior
      - tlp
      - tlp-rdw
      - tmux
      - tree
      - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
      - unzip
      - wget
      - whois
      - vim
      - vim-pathogen
      - vim-gtk3
      - vim-syntastic
      - vim-syntax-docker
      - vlc
      - xclip # to manipulate the clipboard
      - xournal # drawing note taking and PDF annotation software
      - xstow
      - youtube-dl
      - zip
      - zsh
      - zsh-syntax-highlighting
    state: latest

- name: Install python packages
  pip:
    name:
      #- aws-cli
      - termtime
      - bpytop
