- name: Install Fedora specific packages
  when: ansible_distribution == 'Fedora'
  ansible.builtin.package:
    name:
      - yum-plugin-priorities
      - epel-release

- name: Install Ubuntu specific packages
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.package:
    name:
      - bambam # baby keyboard mashing software

- name: Install Jujhar's Software
  ignore_errors: true
  ignore_unreachable: true
  ansible.builtin.package:
    name:
      - audacity
      - bmon
      - build-essential
      - chrome-gnome-shell
      - chromium-browser
      - clamav
      - clamav-daemon
      - clamtk
      - conky
      - curl
      - filezilla
      - firefox
      - forensics-all
      - gcc
      - gimp
      - git
      - gnome
      - gnome-screenshot
      - golang-go
      - grep
      - htop
      - inotify-tools
      - iotop
      - jq
      - lastpass-cli
      - libcanberra-gtk-module
      - libsource-highlight-common
      - liferea # gui rss reader
      - lynx # tui browser
      - make
      - moreutils # additional unix utilities such as lckdo: Executes a program while holding a lock https://itnext.io/8-advanced-linux-command-line-tools-9d81258c3165
      - mycli
      - nautilus-admin
      - nautilus-extension-gnome-terminal
      - nautilus-font-manager
      - nautilus-image-converter
      - nautilus-wipe
      - ncdu
      - nemo # nautilus filemanager replacement
      - nemo # nice file manager
      - nemo-fileroller
      - nemo-font-manager
      - neofetch # get system deets to flex on others
      - net-tools
      - nethogs
      - nfs-client
      - nmap
      - obs-studio # live stream tool
      - openvpn
      - pandoc
      - pass
      - picard # MusicBrainz audio files tagger
      - powertop
      - pwgen
      - python3-pip
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-vnc
      - restic # badass backup
      - rsync
      - shellcheck
      - socat
      - sox # Swiss army knife of sound processing
      - strace # debug system calls
      - tar
      - terminator
      - tig
      - timewarrior
      - tlp
      - tlp-rdw
      - tmux
      - tree
      - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
      - unzip
      - vim
      - vim-gtk3
      - vim-pathogen
      - vim-syntastic
      - vim-syntax-docker
      - vlc
      - wget
      - whois
      - xclip # to manipulate the clipboard
      - xournal # drawing note taking and PDF annotation software
      - xstow
      - youtube-dl
      - zip
      - zsh
      - zsh-syntax-highlighting
    state: latest
