- name: Remove ubuntu dock
  command: apt remove -y gnome-shell-extension-ubuntu-dock
  when: ansible_distribution == 'Ubuntu'

- name: Set max file watches for crashplan inotify.
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=1048576

- name: Install Jujhar sudoers
  copy:
    dest: /etc/sudoers.d/jujhar
    content: jujhar ALL=(ALL) NOPASSWD:ALL
